# Introduzione a Numpy

## Introduzione

Numpy e' una libreria open-source che implementa un tipo di vettore chiamato
*ndarray* (n-dimensional array), che chiameremo banalmente array.
E' una libreria che implementa operazioni sugli array ad altissima efficienza,
di 2 ordini di grandezza piu' veloce rispetto ad analoghe operazioni sulle liste.
Tale efficienza risulta fondamentale per applicazioni di ML, dove l'analisi e la gestione di
milioni di righe e centinaia o migliaia di colonne rende l'efficienza una delle cose piu' importanti. <br>
Centinaia di librerie usano numpy come base per le loro implementazioni: Matplotlib, Pandas, Keras, SciPy ecc..
sono tra le piu' importanti. <br>
Uno dei vantaggi della programmazione con Numpy e' la possibilita' di manipolare i vettori direttamente dall'interno,
senza dover eseguire numerosi cicli for annidati per agire sui suoi oggetti.

## Inport della libreria
La libreria numpy e' inserita tra le distro base di Anaconda. Risulta quindi generalmente preistallata.
Nel caso non lo fosse, o l'ambiente di riferiemnto nel quale viene realizzato il prgetto non lo contenga posso
eseguire: <br>
`!pip install numpy` <br>
Ricordo che il punto esclamativo in una cella Ipython esegue delle operazioni sul terminale.<br>
Per convenzione numpy si importa con alis np:

In [1]:
import numpy as np

## Creazione di un array

In [18]:
# Costriusco l'array con no.array()
mio_array = np.array([0,1,2,3,4,5,6,8])
mio_array

array([0, 1, 2, 3, 4, 5, 6, 8])

In [19]:
# l'array contiene tipi omogenei: solo interi, solo numeri, solo caratteri... 
mio_array = np.array([0,1,2,"a",4,5,6,8])
mio_array # tutti gli elementi diventano di tipo "str"

array(['0', '1', '2', 'a', '4', '5', '6', '8'], dtype='<U11')

In [20]:
# l'array contiene tipi omogenei: solo interi, solo numeri, solo caratteri... 
mio_array = np.array([0.0 ,1,2,3,4,5,6,8])
mio_array # tutti gli elementi diventano di tipo "float"

array([0., 1., 2., 3., 4., 5., 6., 8.])

In [21]:
# l'array contiene tipi omogenei: solo interi, solo numeri, solo caratteri... 
mio_array = np.array([0.0 ,1,"a",3,4,5,6,8])
mio_array # tutti gli elementi diventano di tipo "str"

array(['0.0', '1', 'a', '3', '4', '5', '6', '8'], dtype='<U32')

In [23]:
mio_array = np.array([[0,1,2,3,4,5,6,8]])
mio_array

array([[0, 1, 2, 3, 4, 5, 6, 8]])

### Array multidimensionali

In [26]:
mio_array = np.array([[2,3] ,[4,5] , [6,7]  ])
mio_array

array([[2, 3],
       [4, 5],
       [6, 7]])

In [32]:
# e gli propongo di costruire un array con dimensioni non omogenee, dice che non gli picae:
mio_array = np.array([[2,3] ,[4,5] , [6 ]  ])
mio_array

C:\Users\simon\AppData\Local\Temp/ipykernel_11048/1719352565.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  mio_array = np.array([[2,3] ,[4,5] , [6 ]  ])


array([list([2, 3]), list([4, 5]), list([6])], dtype=object)

## Proprieta' di un array:

### `.dtype`

Restituisce il tipo degli oggeti contenuti: 

In [36]:
mio_array = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [39]:
mio_array.dtype

dtype('int32')

In [43]:
array_vuoto = np.array([])
array_vuoto.dtype

dtype('float64')

In [44]:
mio_array = np.array([[2,3] ,[4,5] , [6 ]  ])
mio_array.dtype

C:\Users\simon\AppData\Local\Temp/ipykernel_11048/1643552141.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  mio_array = np.array([[2,3] ,[4,5] , [6 ]  ])


dtype('O')

In [45]:
mio_array = np.array([[1.0,2,3], [4,5,6], [7,8,9]])
mio_array.dtype

dtype('float64')

In [46]:
mio_array = np.array([[1.0,2,3], [4,5,6], [7,8,9]], dtype= "float32")
mio_array.dtype

dtype('float32')

### `.shape`

Restituisce una tupla contenente nell'ordine il numero di righe e il numero di colonne dell'array:
`(r,c)`

In [52]:
mio_array = np.array([[1,2], [2,3], [3,4]])
mio_array

array([[1, 2],
       [2, 3],
       [3, 4]])

In [53]:
mio_array.shape

(3, 2)

In [59]:
num_righe = mio_array.shape[0]
num_righe

3

In [58]:
num_colonne = mio_array.shape[1]
num_colonne

2

## Iterare su un array: 
Nonostante sia poco efficiente e spesso inutile, si puo' iterare su un array. Esso e' iterabile.

In [64]:
mio_array = np.array([1,2,3,4,5])
mio_array

array([1, 2, 3, 4, 5])

In [65]:
for elem in mio_array:
    print(elem)

1
2
3
4
5


In [66]:
mio_array

array([1, 2, 3, 4, 5])

In [68]:
mio_array + 2 

array([3, 4, 5, 6, 7])

In [142]:
5 * np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [141]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Creare un array a partire da intervalli: 

### `arange()` 

In [70]:
mio_array = np.array([1,2,3,4,5])
mio_array

array([1, 2, 3, 4, 5])

In [78]:
mio_array = np.arange(1,10,.2)
mio_array

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

### `linspace()`


In [86]:
mio_array = np.linspace(1,10,20)
print(len(mio_array), " valori")
mio_array

20  valori


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [87]:
mio_array = np.linspace(1,10,30)
print(len(mio_array), " valori")
mio_array

30  valori


array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [88]:
mio_array = np.linspace(1,10,30, endpoint=False)
print(len(mio_array), " valori")
mio_array

30  valori


array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9, 5.2, 5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5,
       8.8, 9.1, 9.4, 9.7])

In [91]:
mio_array = np.linspace(1,10,30, endpoint=False)
print(len(mio_array), " valori")
mio_array

30  valori


array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9, 5.2, 5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5,
       8.8, 9.1, 9.4, 9.7])

### `logspace(start, stop, num=50, base = 10)` 
Crea un array di 50 elementi (num) da `base**start` a `base **stop`

In [99]:
np.logspace(1,5, num=5, base = 2)

array([ 2.,  4.,  8., 16., 32.])

In [92]:
np.linspace(1,100_000, 5)

array([1.000000e+00, 2.500075e+04, 5.000050e+04, 7.500025e+04,
       1.000000e+05])

## Prestazoni di array e liste

In [ ]:
# %%time
import random

%timeit -r 8 a = [random.randint(1,7) for j in range(6_000)]

In [118]:
%timeit a = np.random.randint(1,7,600_000_000)

4.76 s ± 34.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [114]:
a = np.random.randint(1,7,60_000_000)

In [8]:
import random

%timeit rolls = [random.randrange(1,7) for j in range(6_000_000)]

4.82 s ± 260 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
import numpy

%timeit rolls_array = np.random.randint(1,7,6_000_000)

50.4 ms ± 229 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit rolls_array = np.random.randint(1,7,60_000_000)

497 ms ± 9.71 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
%timeit rolls_array = np.random.randint(1,7,600_000_000)

4.92 s ± 17.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Metodi di calcolo su Numpy

In [122]:
mio_array = np.arange(10)
mio_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
# somme
5 + mio_array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [124]:
# moltiplicazioni
5 * mio_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [125]:
# elevamenti a potenza
2 ** mio_array

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

In [126]:
mio_array ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [127]:
10 / mio_array

C:\Users\simon\AppData\Local\Temp/ipykernel_11048/1330181607.py:1: RuntimeWarning: divide by zero encountered in true_divide
  10 / mio_array


array([        inf, 10.        ,  5.        ,  3.33333333,  2.5       ,
        2.        ,  1.66666667,  1.42857143,  1.25      ,  1.11111111])

In [129]:
mio_array / 10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [136]:
# Broadcasting
5 * mio_array 
# e' equivalente a
np.array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]) * mio_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

### Operatori di calcolo


In [137]:
mio_array.max()

9

In [138]:
mio_array.min()

0

In [139]:
mio_array.mean()

4.5

## Indexing

In [7]:
mio_array = np.random.randint(1, 10,(3,5))
mio_array

array([[7, 4, 1, 5, 3],
       [6, 6, 9, 2, 4],
       [8, 1, 9, 9, 8]])

Per eseguire lo slicing su un array si utilizza pressoche' la stessa modalita' che si utilizza per le stringhe:
* Per estrarre la riga `n`:
  - `mio_array[n]`
* Per estrarre la colonna `m`:
  - `mio_array[:,m]`
* Per stampare le righe dalla `r0` alla `rn`(esclusa) e le colonne dalla `c0` alla `cn`(esclusa):
  - `mio_array[r0:rn,c0:cn]`
* Per creare una copia dell'array contenente tutte le righe e le colonne:
  - `mio_array[:,:]`

`:` e' una porzione dell'array che contiene tutte le righe/colonne

In [8]:
# crea una array unidimensionale con i dati della prima riga:
mio_array[0]

array([7, 4, 1, 5, 3])

In [10]:
# le prime due righe:
mio_array[:2]

array([[7, 4, 1, 5, 3],
       [6, 6, 9, 2, 4]])

In [13]:
# la prima colonna:
mio_array[:,0]

array([7, 6, 8])

In [14]:
# una copia dell'array contenente tutte le righe e le colonne:
mio_array[:,:]

array([[7, 4, 1, 5, 3],
       [6, 6, 9, 2, 4],
       [8, 1, 9, 9, 8]])

## Copia di un array: copie superficiali e copie profonde

In [15]:
mio_array = np.ones((3,4))
mio_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
copia_superficiale_di_mio_array = mio_array

In [19]:
mio_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
mio_array[0] = 2
mio_array

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
copia_superficiale_di_mio_array

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
id(mio_array)

2459038634320

In [23]:
id(copia_superficiale_di_mio_array)

2459038634320

In [24]:
copia_profonda_mio_array = mio_array.copy()

In [25]:
copia_superficiale_di_mio_array

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
id(copia_profonda_mio_array)

2459038587376

In [27]:
id(mio_array)

2459038634320

In [28]:
mio_array += 20

In [29]:
mio_array

array([[22., 22., 22., 22.],
       [21., 21., 21., 21.],
       [21., 21., 21., 21.]])

In [30]:
copia_profonda_mio_array

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Reshaping e Trasposizioni