# Introduzione a Numpy

## Introduzione

Numpy e' una libreria open-source che implementa un tipo di vettore chiamato
*ndarray* (n-dimensional array), che chiameremo banalmente array.
E' una libreria che implementa operazioni sugli array ad altissima efficienza,
di 2 ordini di grandezza piu' veloce rispetto ad analoghe operazioni sulle liste.
Tale efficienza risulta fondamentale per applicazioni di ML, dove l'analisi e la gestione di
milioni di righe e centinaia o migliaia di colonne rende l'efficienza una delle cose piu' importanti. <br>
Centinaia di librerie usano numpy come base per le loro implementazioni: Matplotlib, Pandas, Keras, SciPy ecc..
sono tra le piu' importanti. <br>
Uno dei vantaggi della programmazione con Numpy e' la possibilita' di manipolare i vettori direttamente dall'interno,
senza dover eseguire numerosi cicli for annidati per agire sui suoi oggetti.

## Inport della libreria
La libreria numpy e' inserita tra le distro base di Anaconda. Risulta quindi generalmente preistallata.
Nel caso non lo fosse, o l'ambiente di riferiemnto nel quale viene realizzato il prgetto non lo contenga posso
eseguire: <br>
`!pip install numpy` <br>
Ricordo che il punto esclamativo in una cella Ipython esegue delle operazioni sul terminale.<br>
Per convenzione numpy si importa con alis np:

In [1]:
import numpy as np

In [4]:
np.__version__  # double underscore dunder

'1.21.4'

## Creazione di un array

In [18]:
# Costriusco l'array con no.array()
mio_array = np.array([0,1,2,3,4,5,6,8])
mio_array

array([0, 1, 2, 3, 4, 5, 6, 8])

In [5]:
# l'array contiene tipi omogenei: solo interi, solo numeri, solo caratteri... 
mio_array = np.array([0,1,2,"ab",4,5,6,8])
mio_array # tutti gli elementi diventano di tipo "str"

array(['0', '1', '2', 'ab', '4', '5', '6', '8'], dtype='<U11')

In [20]:
# l'array contiene tipi omogenei: solo interi, solo numeri, solo caratteri... 
mio_array = np.array([0.0 ,1,2,3,4,5,6,8])
mio_array # tutti gli elementi diventano di tipo "float"

array([0., 1., 2., 3., 4., 5., 6., 8.])

In [21]:
# l'array contiene tipi omogenei: solo interi, solo numeri, solo caratteri... 
mio_array = np.array([0 ,1,"a",3,4,5,6,8])
mio_array # tutti gli elementi diventano di tipo "str"

array(['0.0', '1', 'a', '3', '4', '5', '6', '8'], dtype='<U32')

In [8]:
mio_array = np.array([[0,1,2,3,4,5,6,8]])
mio_array

array([[0, 1, 2, 3, 4, 5, 6, 8]])

### Array multidimensionali

In [26]:
mio_array = np.array([[2,3] ,[4,5] , [6,7]  ])
mio_array

array([[2, 3],
       [4, 5],
       [6, 7]])

In [32]:
# e gli propongo di costruire un array con dimensioni non omogenee, dice che non gli piace:
mio_array = np.array([[2,3] ,[4,5] , [6 ]  ])
mio_array

C:\Users\simon\AppData\Local\Temp/ipykernel_11048/1719352565.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  mio_array = np.array([[2,3] ,[4,5] , [6 ]  ])


array([list([2, 3]), list([4, 5]), list([6])], dtype=object)

## Proprieta' di un array:

### `.dtype`

Restituisce il tipo degli oggeti contenuti:

In [9]:
mio_array = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [10]:
mio_array.dtype

dtype('int32')

In [11]:
array_vuoto = np.array(["a"])
array_vuoto.dtype

dtype('<U1')

In [12]:
mio_array = np.array([[2,3] ,[4,5] , [6 ]  ])
mio_array.dtype

C:\Users\simon\AppData\Local\Temp/ipykernel_7268/1384331432.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  mio_array = np.array([[2,3] ,[4,5] , [6 ]  ])


dtype('O')

In [45]:
mio_array = np.array([[1.0,2,3], [4,5,6], [7,8,9]])
mio_array.dtype

dtype('float64')

In [46]:
mio_array = np.array([[1.0,2,3], [4,5,6], [7,8,9]], dtype= "float32")
mio_array.dtype

dtype('float32')

### `.shape`

Restituisce una tupla contenente nell'ordine il numero di righe e il numero di colonne dell'array:
`(r,c)`

In [52]:
mio_array = np.array([[1,2], [2,3], [3,4]])
mio_array

array([[1, 2],
       [2, 3],
       [3, 4]])

In [53]:
mio_array.shape

(3, 2)

In [59]:
num_righe = mio_array.shape[0]
num_righe

3

In [58]:
num_colonne = mio_array.shape[1]
num_colonne

2

## Iterare su un array: 
Nonostante sia poco efficiente e spesso inutile, si puo' iterare su un array. Esso e' iterabile.

In [64]:
mio_array = np.array([1,2,3,4,5])
mio_array

array([1, 2, 3, 4, 5])

In [65]:
for elem in mio_array:
    print(elem)

1
2
3
4
5


In [66]:
mio_array

array([1, 2, 3, 4, 5])

In [68]:
mio_array + 2 

array([3, 4, 5, 6, 7])

In [13]:
np.ones(10) * 5 # Crea un array fatto di 1 con 10 elementi e moltiplica per 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [141]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Creare un array a partire da intervalli: 

### `arange()` 

In [16]:
mio_array = np.array([1,2,3,4,5])
mio_array

array([1, 2, 3, 4, 5])

In [17]:
# Usando `.arange(Start,Stop,Step)` la cella precedente diventa:
mio_array = np.arange(1,6)
mio_array

array([1, 2, 3, 4, 5])

In [78]:
# Funziona anche con le cifre decimali:
mio_array = np.arange(1,10,.2)
mio_array

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

### `linspace(Start, Stop, NumeroDiElementi)`
Crea un array di N elementi suddividendo in parti uguali lo spazio compreso tra Start e Stop (compreso)


In [86]:
mio_array = np.linspace(1,10,20)
print(len(mio_array), " valori")
mio_array

20  valori


array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [87]:
mio_array = np.linspace(1,10,30)
print(len(mio_array), " valori")
mio_array

30  valori


array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [20]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [18]:
# Posso specificare di escludere l'elemento di "Stop" e anche di restituire lo Step che
# e' stato calcolato
# Se uso Retstep la funzione non restituisce piu' un "Array" ma una tupla con due elementi
# di cui il primo e' l'array e il secondo e' lo step

mio_array = np.linspace(1,10,30, endpoint=False, retstep=True)
print(len(mio_array), " valori")
mio_array

2  valori


(array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
        4.9, 5.2, 5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5,
        8.8, 9.1, 9.4, 9.7]),
 0.3)

In [91]:
mio_array = np.linspace(1,10,30, endpoint=False)
print(len(mio_array), " valori")
mio_array

30  valori


array([1. , 1.3, 1.6, 1.9, 2.2, 2.5, 2.8, 3.1, 3.4, 3.7, 4. , 4.3, 4.6,
       4.9, 5.2, 5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5,
       8.8, 9.1, 9.4, 9.7])

### `logspace(start, stop, num=50, base = 10)` 
Crea un array di 50 elementi (num) da `base**start` a `base **stop`

In [21]:
np.logspace(1,5, num=10, base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [92]:
np.linspace(1,100_000, 5)

array([1.000000e+00, 2.500075e+04, 5.000050e+04, 7.500025e+04,
       1.000000e+05])

## Prestazoni di array e liste

In [22]:
# %%time
import random

%timeit -r 8 a = [random.randint(1,7) for j in range(6_000)]

5.33 ms ± 40.5 µs per loop (mean ± std. dev. of 8 runs, 100 loops each)


In [24]:
%timeit a = np.random.randint(1,7,600_000)

5.35 ms ± 27.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [114]:
a = np.random.randint(1,7,60_000_000)

In [8]:
import random

%timeit rolls = [random.randrange(1,7) for j in range(6_000_000)]

4.82 s ± 260 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
import numpy

%timeit rolls_array = np.random.randint(1,7,6_000_000)

50.4 ms ± 229 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit rolls_array = np.random.randint(1,7,60_000_000)

497 ms ± 9.71 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
%timeit rolls_array = np.random.randint(1,7,600_000_000)

4.92 s ± 17.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Metodi di calcolo su Numpy

In [26]:
mio_array = np.arange(10)
mio_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
# somme
5 + mio_array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [124]:
# moltiplicazioni
5 * mio_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [125]:
# elevamenti a potenza
2 ** mio_array

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512], dtype=int32)

In [126]:
mio_array ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [29]:
array_con_inf = 10 / mio_array
print(array_con_inf.dtype)
array_con_inf

float64


C:\Users\simon\AppData\Local\Temp/ipykernel_7268/1329135763.py:1: RuntimeWarning: divide by zero encountered in true_divide
  array_con_inf = 10 / mio_array


array([        inf, 10.        ,  5.        ,  3.33333333,  2.5       ,
        2.        ,  1.66666667,  1.42857143,  1.25      ,  1.11111111])

In [129]:
mio_array / 10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [136]:
# Broadcasting
5 * mio_array 
# e' equivalente a
np.array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5]) * mio_array

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [137]:
mio_array.max()

9

In [138]:
mio_array.min()

0

In [139]:
mio_array.mean()

4.5

## Indexing

In [34]:
mio_array = np.random.randint(1, 100,(12,15))
mio_array

array([[ 3, 50, 50, 33, 25, 57, 97, 26, 37, 79, 51, 85, 81, 76, 20],
       [31, 30, 58, 85, 82, 99, 59, 19, 50, 53, 17, 56, 93, 42, 66],
       [12, 55, 76, 25, 44,  3, 33, 50, 13, 82, 39, 14, 38, 79, 21],
       [14, 56, 44, 34, 97, 82, 97, 85, 54, 46, 64, 68, 61, 97, 23],
       [96, 14, 68, 11, 96,  1, 16, 16, 73, 54,  6, 53, 30, 25, 76],
       [24, 31, 10, 98, 15, 86, 34, 81, 26, 98, 38, 31, 19, 15, 73],
       [39, 90, 79, 19, 94, 19, 94, 86, 66, 97, 63, 47, 34, 79, 86],
       [66, 71, 89, 55, 43, 45, 55, 68,  2, 69, 20, 57, 97, 36, 95],
       [91, 49, 98, 17, 81, 83, 41,  6, 67, 74, 57, 60, 23, 84, 94],
       [18, 56, 35, 63, 85, 65, 37, 82,  8, 47, 66, 76, 22, 96, 85],
       [61, 47, 53, 52, 37, 64, 65, 78, 21, 66, 52,  3, 42, 80, 66],
       [60, 50, 77, 90, 47,  6, 53, 21, 94, 81, 54, 10, 25,  9, 77]])

Per eseguire lo slicing su un array si utilizza pressoche' la stessa modalita' che si utilizza per le stringhe:
* Per estrarre la riga `n`:
  - `mio_array[n]`
* Per estrarre la colonna `m`:
  - `mio_array[:,m]`
* Per stampare le righe dalla `r0` alla `rn`(esclusa) e le colonne dalla `c0` alla `cn`(esclusa):
  - `mio_array[r0:rn,c0:cn]`
* Per creare una copia dell'array contenente tutte le righe e le colonne:
  - `mio_array[:,:]`

`:` e' una porzione dell'array che contiene tutte le righe/colonne

In [39]:
# crea una array unidimensionale con i dati della prima riga:
mio_array[0]

array([ 3, 50, 50, 33, 25, 57, 97, 26, 37, 79, 51, 85, 81, 76, 20])

In [40]:
# le prime due righe:
mio_array[:2] # 

array([[ 3, 50, 50, 33, 25, 57, 97, 26, 37, 79, 51, 85, 81, 76, 20],
       [31, 30, 58, 85, 82, 99, 59, 19, 50, 53, 17, 56, 93, 42, 66]])

In [41]:
# la prima colonna:
mio_array[:,0]

array([ 3, 31, 12, 14, 96, 24, 39, 66, 91, 18, 61, 60])

In [42]:
# dalla terza alla settima riga compresa
mio_array[2:8]

array([[14, 56, 44, 34, 97, 82, 97, 85, 54, 46, 64, 68, 61, 97, 23],
       [96, 14, 68, 11, 96,  1, 16, 16, 73, 54,  6, 53, 30, 25, 76],
       [24, 31, 10, 98, 15, 86, 34, 81, 26, 98, 38, 31, 19, 15, 73],
       [39, 90, 79, 19, 94, 19, 94, 86, 66, 97, 63, 47, 34, 79, 86],
       [66, 71, 89, 55, 43, 45, 55, 68,  2, 69, 20, 57, 97, 36, 95]])

In [43]:
# dalla terza alla settima colonna compresa
mio_array[:,2:8]

array([[50, 33, 25, 57, 97, 26],
       [58, 85, 82, 99, 59, 19],
       [76, 25, 44,  3, 33, 50],
       [44, 34, 97, 82, 97, 85],
       [68, 11, 96,  1, 16, 16],
       [10, 98, 15, 86, 34, 81],
       [79, 19, 94, 19, 94, 86],
       [89, 55, 43, 45, 55, 68],
       [98, 17, 81, 83, 41,  6],
       [35, 63, 85, 65, 37, 82],
       [53, 52, 37, 64, 65, 78],
       [77, 90, 47,  6, 53, 21]])

In [44]:
# dalla terza alla settima riga e dalla terza alla settima colonna compresa
mio_array[2:8,2:8]

array([[76, 25, 44,  3, 33, 50],
       [44, 34, 97, 82, 97, 85],
       [68, 11, 96,  1, 16, 16],
       [10, 98, 15, 86, 34, 81],
       [79, 19, 94, 19, 94, 86],
       [89, 55, 43, 45, 55, 68]])

In [46]:
# una copia dell'array contenente tutte le righe e le colonne:
a = mio_array[:,:]

In [49]:
a[0] = 1
a

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [31, 30, 58, 85, 82, 99, 59, 19, 50, 53, 17, 56, 93, 42, 66],
       [12, 55, 76, 25, 44,  3, 33, 50, 13, 82, 39, 14, 38, 79, 21],
       [14, 56, 44, 34, 97, 82, 97, 85, 54, 46, 64, 68, 61, 97, 23],
       [96, 14, 68, 11, 96,  1, 16, 16, 73, 54,  6, 53, 30, 25, 76],
       [24, 31, 10, 98, 15, 86, 34, 81, 26, 98, 38, 31, 19, 15, 73],
       [39, 90, 79, 19, 94, 19, 94, 86, 66, 97, 63, 47, 34, 79, 86],
       [66, 71, 89, 55, 43, 45, 55, 68,  2, 69, 20, 57, 97, 36, 95],
       [91, 49, 98, 17, 81, 83, 41,  6, 67, 74, 57, 60, 23, 84, 94],
       [18, 56, 35, 63, 85, 65, 37, 82,  8, 47, 66, 76, 22, 96, 85],
       [61, 47, 53, 52, 37, 64, 65, 78, 21, 66, 52,  3, 42, 80, 66],
       [60, 50, 77, 90, 47,  6, 53, 21, 94, 81, 54, 10, 25,  9, 77]])

In [50]:
mio_array

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [31, 30, 58, 85, 82, 99, 59, 19, 50, 53, 17, 56, 93, 42, 66],
       [12, 55, 76, 25, 44,  3, 33, 50, 13, 82, 39, 14, 38, 79, 21],
       [14, 56, 44, 34, 97, 82, 97, 85, 54, 46, 64, 68, 61, 97, 23],
       [96, 14, 68, 11, 96,  1, 16, 16, 73, 54,  6, 53, 30, 25, 76],
       [24, 31, 10, 98, 15, 86, 34, 81, 26, 98, 38, 31, 19, 15, 73],
       [39, 90, 79, 19, 94, 19, 94, 86, 66, 97, 63, 47, 34, 79, 86],
       [66, 71, 89, 55, 43, 45, 55, 68,  2, 69, 20, 57, 97, 36, 95],
       [91, 49, 98, 17, 81, 83, 41,  6, 67, 74, 57, 60, 23, 84, 94],
       [18, 56, 35, 63, 85, 65, 37, 82,  8, 47, 66, 76, 22, 96, 85],
       [61, 47, 53, 52, 37, 64, 65, 78, 21, 66, 52,  3, 42, 80, 66],
       [60, 50, 77, 90, 47,  6, 53, 21, 94, 81, 54, 10, 25,  9, 77]])

## Copia di un array: copie superficiali e copie profonde

In [73]:
mio_array = np.ones((3,4))
mio_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [74]:
# Se assegno un array ad una variabile sto creando una copia superficiale
# In pratica l'oggetto resta uno solo, ma creo due "nomi" per lo stesso oggetto
copia_superficiale_di_mio_array = mio_array

In [75]:
mio_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
copia_superficiale_di_mio_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [77]:
# Se modifico degli elementi in uno dei due oggetti le modifiche si 
# riflettono su entrambi
mio_array[0] = 2
mio_array

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
copia_superficiale_di_mio_array

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [79]:
id(mio_array)

1429593020528

In [80]:
id(copia_superficiale_di_mio_array)

1429593020528

In [81]:
mio_array is copia_superficiale_di_mio_array

True

In [83]:
# Per creare una VERA copia del mio oggetto, e quindi un'altro oggetto
# devo utilizzare il comando '.copy()'
copia_profonda_mio_array = mio_array.copy()

In [84]:
copia_profonda_mio_array

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [85]:
id(copia_profonda_mio_array)

1429592951184

In [86]:
id(mio_array)

1429593020528

In [87]:
mio_array is copia_profonda_mio_array

False

In [88]:
mio_array[0] = 10

In [89]:
mio_array

array([[10., 10., 10., 10.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [90]:
copia_profonda_mio_array

array([[2., 2., 2., 2.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Filtri

In [97]:
mio_array = np.random.randint(0,200,(6,7))
mio_array

array([[190,  69, 192,  88, 137,  85,   7],
       [ 41, 180, 196, 122, 194,  64,   5],
       [175, 113, 171, 157,  24, 111,  20],
       [101,  26, 107, 105, 126,   0,  69],
       [103, 109,   3,  41, 148, 115,  78],
       [ 12,   5, 124,  88,  26,  85, 139]])

In [98]:
# Quali elementi sono maggiori di 100
mio_array[mio_array>100] = 1000
mio_array


array([[1000,   69, 1000,   88, 1000,   85,    7],
       [  41, 1000, 1000, 1000, 1000,   64,    5],
       [1000, 1000, 1000, 1000,   24, 1000,   20],
       [1000,   26, 1000, 1000, 1000,    0,   69],
       [1000, 1000,    3,   41, 1000, 1000,   78],
       [  12,    5, 1000,   88,   26,   85, 1000]])

In [99]:
mio_array[mio_array<10] = -100
mio_array


array([[1000,   69, 1000,   88, 1000,   85, -100],
       [  41, 1000, 1000, 1000, 1000,   64, -100],
       [1000, 1000, 1000, 1000,   24, 1000,   20],
       [1000,   26, 1000, 1000, 1000, -100,   69],
       [1000, 1000, -100,   41, 1000, 1000,   78],
       [  12, -100, 1000,   88,   26,   85, 1000]])

## Reshaping e Trasposizioni

In [104]:
mio_array = np.random.randint(0,20,(2,10))
print(mio_array)
mio_array_reshaped = mio_array.reshape((4,5))
print(mio_array_reshaped)

[[16  5 19  3 11 13  9 10  5 14]
 [ 7  4  1 10 16  9  7  7 10 10]]
[[16  5 19  3 11]
 [13  9 10  5 14]
 [ 7  4  1 10 16]
 [ 9  7  7 10 10]]


In [105]:
mio_array[0] = 0
mio_array

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 7,  4,  1, 10, 16,  9,  7,  7, 10, 10]])

In [106]:
mio_array_reshaped

array([[ 0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0],
       [ 7,  4,  1, 10, 16],
       [ 9,  7,  7, 10, 10]])

In [114]:
mio_array = np.random.randint(0,20,(2,10))
print(mio_array)
mio_array_reshaped = mio_array.reshape((4,4))
print(mio_array_reshaped)

[[16 12  5 12 18  5  8 14  3  4]
 [ 8  6 10  2 10 12 15  0 13  5]]


ValueError: cannot reshape array of size 20 into shape (4,4)

In [109]:
mio_array = np.random.randint(0,20,(2,10))
print(mio_array)
mio_array.resize((4,5))
print(mio_array)

[[ 9  7 19  9  9  7 16  4  1 10]
 [14  2 11 19  4 12 18  2 16  7]]
[[ 9  7 19  9  9]
 [ 7 16  4  1 10]
 [14  2 11 19  4]
 [12 18  2 16  7]]


In [110]:
mio_array = np.random.randint(0,20,(2,10))
print(mio_array)
mio_array.resize((4,4))
print(mio_array)

[[17  3  1  0 18 12  6  7 15 17]
 [ 2 19  6 16  6  9  0 19 10  2]]
[[17  3  1  0]
 [18 12  6  7]
 [15 17  2 19]
 [ 6 16  6  9]]


In [113]:
mio_array = np.random.randint(0,20,(2,10))
print(mio_array)
mio_array.resize((4,8))
print(mio_array)

[[ 5 12  9 16 12 12 13  1  7 14]
 [13 10  7 10 10  4  1  1 16  2]]
[[ 5 12  9 16 12 12 13  1]
 [ 7 14 13 10  7 10 10  4]
 [ 1  1 16  2  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]


In [123]:
a = np.array([["a", "a", "a", "a", "a"],["a", "a", "a", "a", "a"]])
a.resize((10,10))
a

array([['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U1')

`reshape`: crea una nuova vista del mio array originario, con una copia superficiale, dandogli una nuova forma. La forma originale e finale devono avere dimensioni compatibili.
`resize`: modifica l'array che chiama la funzione, cancellando di fatto l'array originario. Se l'array originale ha meno elementi di quello finale vengono aggiunti degli zeri, al contrario invece viene tagliato in coda

In [125]:
mio_array = np.random.randint(1,10,(5,2))
mio_array

array([[1, 5],
       [9, 4],
       [4, 2],
       [6, 4],
       [3, 4]])

In [128]:
mio_array_flattened = mio_array.flatten()
mio_array_flattened

array([1, 5, 9, 4, 4, 2, 6, 4, 3, 4])

In [129]:
mio_array[0] = -10
mio_array

array([[-10, -10],
       [  9,   4],
       [  4,   2],
       [  6,   4],
       [  3,   4]])

In [130]:
mio_array_flattened

array([1, 5, 9, 4, 4, 2, 6, 4, 3, 4])

In [131]:
mio_array = np.random.randint(1,10,(5,2))
mio_array

array([[7, 1],
       [9, 3],
       [3, 4],
       [5, 6],
       [7, 7]])

In [136]:
mio_array_ravel = mio_array.ravel()
mio_array_ravel

array([7, 1, 9, 3, 3, 4, 5, 6, 7, 7])

In [137]:
mio_array[0] = 0
mio_array

array([[0, 0],
       [9, 3],
       [3, 4],
       [5, 6],
       [7, 7]])

In [138]:
mio_array_ravel

array([0, 0, 9, 3, 3, 4, 5, 6, 7, 7])

`flatten`: crea una copia profonda dell'array originale appiattito
`ravel`: crea una nuova vista dell'array originale con una nuova forma appiattita

In [139]:
mio_array = np.random.randint(1,10,(5,2))
mio_array

array([[9, 7],
       [1, 9],
       [8, 3],
       [1, 3],
       [4, 5]])

In [141]:
mio_array_T  = mio_array.T

In [143]:
mio_array[0] = 100
mio_array

array([[100, 100],
       [  1,   9],
       [  8,   3],
       [  1,   3],
       [  4,   5]])

In [144]:
mio_array_T 

array([[100,   1,   8,   1,   4],
       [100,   9,   3,   3,   5]])

`T`: crea una nuova vista trasposta dell'array originale

In [152]:
array1 = np.array([[-1,0],[1,2]])
array1

array([[-1,  0],
       [ 1,  2]])

In [151]:
array2 = np.array([[3,4],[5,6]])
array2

array([[3, 4],
       [5, 6]])

In [161]:
a1_a2 = np.hstack((array2 , array1))
a1_a2

array([[   3,    4, -100, -100],
       [   5,    6,    1,    2]])

In [157]:
array1[0] = -100
array1

array([[-100, -100],
       [   1,    2]])

In [158]:
a1_a2

array([[ 3,  4, -1,  0],
       [ 5,  6,  1,  2]])

In [160]:
a1_a2 = np.vstack((array2 , array1))
a1_a2

array([[   3,    4],
       [   5,    6],
       [-100, -100],
       [   1,    2]])

In [164]:
array3 = np.ones((7,2))
array3

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [165]:
np.vstack((array1 , array3))

array([[-100., -100.],
       [   1.,    2.],
       [   1.,    1.],
       [   1.,    1.],
       [   1.,    1.],
       [   1.,    1.],
       [   1.,    1.],
       [   1.,    1.],
       [   1.,    1.]])

In [166]:
np.hstack((array1 , array3))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 7

`hstack`: impilamento di piu' array lungo l'orizzontale - metti i due array uno a fianco dell'altro. Il risultato e' un nuovo array.
`vstack`: impilamento di piu' array lungo la verticale - metti i due array uno sopra dell'altro. Il risultato e' un nuovo array.

Il numero di righe o colonne deve essere lo stesso rispettivamente nello stack orizzontale e verticale.

