<h1>Numpy: Esercizi risolti<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Importa-Numpy-e-visualizza-la-verisone" data-toc-modified-id="Importa-Numpy-e-visualizza-la-verisone-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Importa Numpy e visualizza la verisone</a></span></li><li><span><a href="#Crea-un-arrai-1D-di-numeri-da-0-a-9" data-toc-modified-id="Crea-un-arrai-1D-di-numeri-da-0-a-9-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Crea un arrai 1D di numeri da 0 a 9</a></span></li><li><span><a href="#Crea-un-array-5x5-di-valori-booleani-di-tutti-False" data-toc-modified-id="Crea-un-array-5x5-di-valori-booleani-di-tutti-False-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Crea un array 5x5 di valori booleani di tutti False</a></span></li><li><span><a href="#Dall'array-definito-in-&quot;arr&quot;-estrai-tutti-i-numeri-pari:" data-toc-modified-id="Dall'array-definito-in-&quot;arr&quot;-estrai-tutti-i-numeri-pari:-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Dall'array definito in "arr" estrai tutti i numeri pari:</a></span></li><li><span><a href="#Sostituisci-i-valori-di-arr-con-il-valore-100-senza-modificare-arr" data-toc-modified-id="Sostituisci-i-valori-di-arr-con-il-valore-100-senza-modificare-arr-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Sostituisci i valori di <code>arr</code> con il valore <code>100</code> senza modificare <code>arr</code></a></span></li><li><span><a href="#Trasforma-un-array-1D-da-10-elementi-in-un-array-2D-5x2-elementi.-Utilizza-la-funzione-reshape." data-toc-modified-id="Trasforma-un-array-1D-da-10-elementi-in-un-array-2D-5x2-elementi.-Utilizza-la-funzione-reshape.-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Trasforma un array 1D da 10 elementi in un array 2D 5x2 elementi. Utilizza la funzione <code>reshape</code>.<br></a></span></li><li><span><a href="#Dati-due-array,-a-e-b:-eseguire-uno-stacking-verticale." data-toc-modified-id="Dati-due-array,-a-e-b:-eseguire-uno-stacking-verticale.-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Dati due array, a e b: eseguire uno stacking verticale.<br></a></span></li><li><span><a href="#Dati-due-array,-a-e-b:-eseguire-uno-stacking-orizzontale." data-toc-modified-id="Dati-due-array,-a-e-b:-eseguire-uno-stacking-orizzontale.-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>Dati due array, a e b: eseguire uno stacking orizzontale.<br></a></span></li><li><span><a href="#Verifica-la-posizione-in-cui-due-array-sono-uguali" data-toc-modified-id="Verifica-la-posizione-in-cui-due-array-sono-uguali-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Verifica la posizione in cui due array sono uguali</a></span></li><li><span><a href="#Estrai-da-un-array-tutti-gli-elementi-che-verificano-una-condizione." data-toc-modified-id="Estrai-da-un-array-tutti-gli-elementi-che-verificano-una-condizione.-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>Estrai da un array tutti gli elementi che verificano una condizione.</a></span></li><li><span><a href="#Convertire-una-funzione-che-restituisce-il-minimo-di-due-numeri-e-opera-normalmente-tra-due-scalari,-affinche-funzioni-con-array:" data-toc-modified-id="Convertire-una-funzione-che-restituisce-il-minimo-di-due-numeri-e-opera-normalmente-tra-due-scalari,-affinche-funzioni-con-array:-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>Convertire una funzione che restituisce il minimo di due numeri e opera normalmente tra due scalari, affinche funzioni con array:</a></span></li><li><span><a href="#Come-scambiare-due-colonne-o-due-righe-in-un-array-2D" data-toc-modified-id="Come-scambiare-due-colonne-o-due-righe-in-un-array-2D-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>Come scambiare due colonne o due righe in un array 2D</a></span></li><li><span><a href="#Come-creare-una-matrice-3-x-4-di-numeri-decimali-randomici-compresi-tra-7-e-12" data-toc-modified-id="Come-creare-una-matrice-3-x-4-di-numeri-decimali-randomici-compresi-tra-7-e-12-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>Come creare una matrice 3 x 4 di numeri decimali randomici compresi tra 7 e 12</a></span></li><li><span><a href="#Stampare-a-monitor-solo-un-array-con-visualizzazione-di-solo-3-cifre-decimali" data-toc-modified-id="Stampare-a-monitor-solo-un-array-con-visualizzazione-di-solo-3-cifre-decimali-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>Stampare a monitor solo un array con visualizzazione di solo 3 cifre decimali</a></span></li><li><span><a href="#Stamapare-a-monitor-solo-un-certo-numero-di-elementi-di-un-array" data-toc-modified-id="Stamapare-a-monitor-solo-un-certo-numero-di-elementi-di-un-array-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>Stamapare a monitor solo un certo numero di elementi di un array</a></span></li><li><span><a href="#Sostituisci-tutti-valori-superiori-o-inferiori-ad-una-soglia-di-cut-off" data-toc-modified-id="Sostituisci-tutti-valori-superiori-o-inferiori-ad-una-soglia-di-cut-off-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>Sostituisci tutti valori superiori o inferiori ad una soglia di cut-off</a></span></li><li><span><a href="#Individua-la-posizione-degli-n-valori-piu'-piccoli-di-un-array" data-toc-modified-id="Individua-la-posizione-degli-n-valori-piu'-piccoli-di-un-array-17"><span class="toc-item-num">17&nbsp;&nbsp;</span>Individua la posizione degli <code>n</code> valori piu' piccoli di un array</a></span></li><li><span><a href="#In-una-struttura-matriciale-trova-la-posizione-e-il-valore-del-massimo-di-ciascuna-riga-e-di-ciascuna-colonna" data-toc-modified-id="In-una-struttura-matriciale-trova-la-posizione-e-il-valore-del-massimo-di-ciascuna-riga-e-di-ciascuna-colonna-18"><span class="toc-item-num">18&nbsp;&nbsp;</span>In una struttura matriciale trova la posizione e il valore del massimo di ciascuna riga e di ciascuna colonna</a></span></li><li><span><a href="#Troviamo-elementi-duplicati-all-interno-di-un-array" data-toc-modified-id="Troviamo-elementi-duplicati-all-interno-di-un-array-19"><span class="toc-item-num">19&nbsp;&nbsp;</span>Troviamo elementi duplicati all-interno di un array</a></span></li><li><span><a href="#Eseguire-il-drop-dei-valori-non-disponibili-(drop-na-values):" data-toc-modified-id="Eseguire-il-drop-dei-valori-non-disponibili-(drop-na-values):-20"><span class="toc-item-num">20&nbsp;&nbsp;</span>Eseguire il <code>drop</code> dei valori non disponibili (drop na values):</a></span></li></ul></div>

## Importa Numpy e visualizza la verisone

In [1]:
import numpy as np
import sys

In [2]:
np.__version__

'1.21.4'

## Crea un arrai 1D di numeri da 0 a 9

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Crea un array 5x5 di valori booleani di tutti False

In [4]:
np.full((5,5), False, dtype=bool)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

## Dall'array definito in "arr" estrai tutti i numeri pari:
`arr = np.array([1,2,3,4,5,6,7,8,9])`<br>
Output desiderato:<br>
`array([2,4,6,8])`

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [6]:
arr[arr%2==0]

array([2, 4, 6, 8])

## Sostituisci i valori di `arr` con il valore `100` senza modificare `arr`

In [7]:
arr = np.array([1,2,3,4,5,6,7,8,9])

## Trasforma un array 1D da 10 elementi in un array 2D 5x2 elementi. Utilizza la funzione `reshape`.<br>
`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`<br><br>
Output desiderato:<br>
`array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])`

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## Dati due array, a e b: eseguire uno stacking verticale.<br>
Dati:<br>
```a = array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])
b = array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])
```
Otuput Desiderato:<br><br>
```
array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])
```

In [10]:
a = np.arange(12).reshape(2,-1)

In [11]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [12]:
b = np.full((2,6),100)

In [13]:
b

array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [14]:
np.concatenate((a,b), axis = 0)

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

In [15]:
np.r_[(a,b)]

array([[  0,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11],
       [100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])

## Dati due array, a e b: eseguire uno stacking orizzontale.<br>
Dati:<br>
```
a = array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])
b = array([[100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100]])
```
Otuput Desiderato:
```
array([[  0,   1,   2,   3,   4,   5, 100, 100, 100, 100, 100, 100],
       [  6,   7,   8,   9,  10,  11, 100, 100, 100, 100, 100, 100]])
```

In [16]:
np.concatenate((a,b), axis = 1)

array([[  0,   1,   2,   3,   4,   5, 100, 100, 100, 100, 100, 100],
       [  6,   7,   8,   9,  10,  11, 100, 100, 100, 100, 100, 100]])

In [17]:
np.c_[(a,b)]

array([[  0,   1,   2,   3,   4,   5, 100, 100, 100, 100, 100, 100],
       [  6,   7,   8,   9,  10,  11, 100, 100, 100, 100, 100, 100]])

## Verifica la posizione in cui due array sono uguali

Dati due array della stessa dimensione `a`  `b`, restituire un terzo array contentente la posizione degli elementi di "a" che sono uguali e nello steso posto di analoghi elementi di "b" 
Dati ad esempio:
```
a = np.array([0, 1, 0, 0, 4, 0, 1, 1, 4, 4])
b = np.array([4, 1, 1, 3, 4, 1, 0, 0, 0, 4])
```

Output Desiderato:
`array([1, 4, 9]`

In [18]:
a = np.array([0, 1, 0, 0, 4, 0, 1, 1, 4, 4])

In [19]:
b = np.array([4, 1, 1, 3, 4, 1, 0, 0, 0, 4])

In [20]:
np.where(a == b)

(array([1, 4, 9], dtype=int64),)

## Estrai da un array tutti gli elementi che verificano una condizione.
Estrarre dall'array `a` tutti gli elementi minori o uguali a 5: <br>
Input:<br>
`a = np.array([0,1,2,3,4,5,6,7,8,9])`
<br><br>
Output Desiderato:<br>
`
array([0,1,2,3,4,5])`

In [21]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

In [22]:
a[a<=5]

array([0, 1, 2, 3, 4, 5])

## Convertire una funzione che restituisce il minimo di due numeri e opera normalmente tra due scalari, affinche funzioni con array:

```
def minn(x, y):
    """Get the minimum of two items"""
    if x >= y:
        return y
    else:
        return x
```

Input: <br>
```
a = np.array([4, 0, 1, 5, 1, 8, 5, 2, 9, 4, 2, 5, 2, 7, 4, 0, 5, 9, 6, 7])
b = np.array([1, 5, 1, 5, 6, 7, 3, 4, 3, 8, 9, 8, 6, 4, 5, 3, 9, 2, 3, 9])
```
Output desiderato:<br>
```
array([1, 0, 1, 5, 1, 7, 3, 2, 3, 4, 2, 5, 2, 4, 4, 0, 5, 2, 3, 7])
```

In [23]:
a = np.random.randint(10, size = 20)

In [24]:
b = np.random.randint(10, size = 20)

In [25]:
def minn(x, y):
    """Get the minimum of two items"""
    if x >= y:
        return y
    else:
        return x

In [26]:
minn(10,3)

3

In [27]:
vect_min = np.vectorize(minn)

In [28]:
vect_min(a,b)

array([6, 3, 2, 2, 4, 0, 3, 0, 4, 4, 1, 3, 6, 0, 6, 2, 0, 7, 6, 4])

## Come scambiare due colonne o due righe in un array 2D

In [29]:
arr = np.random.randint(10, size=(3,3))

In [30]:
arr

array([[8, 8, 9],
       [8, 3, 8],
       [2, 4, 6]])

In [31]:
arr[:,[1,0,2]]

array([[8, 8, 9],
       [3, 8, 8],
       [4, 2, 6]])

In [32]:
arr[[2,1,0],:]

array([[2, 4, 6],
       [8, 3, 8],
       [8, 8, 9]])

## Come creare una matrice 3 x 4 di numeri decimali randomici compresi tra 7 e 12

In [33]:
np.set_printoptions(precision=2)
np.random.seed(42)
rand_array = np.random.random(size=(3,4))*(12-7)+7
rand_array

array([[10.88483768,  9.13409871,  9.30991133, 10.704291  ],
       [ 7.34363417,  8.30182106,  8.64423533,  8.68618747],
       [ 7.9778401 ,  7.68256075, 10.29612838, 11.85474094]])

In [34]:
np.set_printoptions(precision=2)
np.random.seed(42)
random_array = np.random.uniform(7,12,size=(3,4))
rand_array

array([[10.88483768,  9.13409871,  9.30991133, 10.704291  ],
       [ 7.34363417,  8.30182106,  8.64423533,  8.68618747],
       [ 7.9778401 ,  7.68256075, 10.29612838, 11.85474094]])

## Stampare a monitor solo un array con visualizzazione di solo 3 cifre decimali

In [35]:
a = np.random.random((4,4))
a

array([[0.09231631, 0.62186154, 0.29994255, 0.27039599],
       [0.25565499, 0.16270456, 0.31246321, 0.77012892],
       [0.6752309 , 0.33922217, 0.89510758, 0.62630339],
       [0.38734683, 0.01840571, 0.93380251, 0.4326235 ]])

In [36]:
np.set_printoptions(precision=3)
a

array([[0.092, 0.622, 0.3  , 0.27 ],
       [0.256, 0.163, 0.312, 0.77 ],
       [0.675, 0.339, 0.895, 0.626],
       [0.387, 0.018, 0.934, 0.433]])

## Stamapare a monitor solo un certo numero di elementi di un array 

In [37]:
long_array = np.arange(100)
long_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [38]:
np.set_printoptions(threshold=6)

In [39]:
long_array

array([ 0,  1,  2, ..., 97, 98, 99])

Per tornare alla visualizzazione non troncata impostare:
`threshold = sys.maxsize`

In [40]:
np.set_printoptions(threshold=sys.maxsize)

In [41]:
long_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Sostituisci tutti valori superiori o inferiori ad una soglia di cut-off
Dato l'array `a`, sostituire tutti i valori inferiori o uguali a 0 con 0, e superiori o uguali a 100 con 100:


In [42]:
np.set_printoptions(precision=2)
np.random.seed(42)
a = np.random.uniform(-100,200,size = (20))
a

array([ 12.36, 185.21, 119.6 ,  79.6 , -53.19, -53.2 , -82.57, 159.85,
        80.33, 112.42, -93.82, 190.97, 149.73, -36.3 , -45.45, -44.98,
        -8.73,  57.43,  29.58, -12.63])

In [43]:
a[a>=100] = 100
a[a<=0] = 0
a

array([ 12.36, 100.  , 100.  ,  79.6 ,   0.  ,   0.  ,   0.  , 100.  ,
        80.33, 100.  ,   0.  , 100.  , 100.  ,   0.  ,   0.  ,   0.  ,
         0.  ,  57.43,  29.58,   0.  ])

In [44]:
np.random.seed(42)
a = np.random.uniform(-100,200,size = (20))
a

array([ 12.36, 185.21, 119.6 ,  79.6 , -53.19, -53.2 , -82.57, 159.85,
        80.33, 112.42, -93.82, 190.97, 149.73, -36.3 , -45.45, -44.98,
        -8.73,  57.43,  29.58, -12.63])

In [45]:
a.clip(0,100)

array([ 12.36, 100.  , 100.  ,  79.6 ,   0.  ,   0.  ,   0.  , 100.  ,
        80.33, 100.  ,   0.  , 100.  , 100.  ,   0.  ,   0.  ,   0.  ,
         0.  ,  57.43,  29.58,   0.  ])

## Individua la posizione degli `n` valori piu' piccoli di un array 
Individua la posizione dei 5 valori piu' piccoli dell'array `a`

In [46]:
np.random.seed(42)
a = np.random.randint(0,100,size = (10), dtype=int)
a

array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74])

In [47]:
np.argsort(a)[:5]

array([2, 5, 0, 4, 3], dtype=int64)

In [48]:
np.argmin(a)

2

## In una struttura matriciale trova la posizione e il valore del massimo di ciascuna riga e di ciascuna colonna 

In [9]:
np.random.seed(42)
matr = np.random.randint(100, size = (3,4))
matr

array([[51, 92, 14, 71],
       [60, 20, 82, 86],
       [74, 74, 87, 99]])

In [10]:
matr.max(axis=0)

array([74, 92, 87, 99])

In [11]:
matr.max(axis=1)

array([92, 86, 99])

In [21]:
np.where(matr == matr.max(axis=0))

(array([0, 2, 2, 2], dtype=int64), array([1, 0, 2, 3], dtype=int64))

In [15]:
np.argsort(matr, axis=0)

array([[0, 1, 0, 0],
       [1, 2, 1, 1],
       [2, 0, 2, 2]], dtype=int64)

In [32]:
matr

array([[51, 92, 14, 71],
       [60, 20, 82, 86],
       [74, 74, 87, 99]])

In [31]:
# indici dei valori massimi di ciascuna colonna
np.argmax(matr, axis = 0)

array([2, 0, 2, 2], dtype=int64)

In [33]:
# indici dei valori massimi di ciascuna riga
np.argmax(matr, axis = 1)

array([1, 3, 3], dtype=int64)

In [34]:
np.argsort(matr)


array([[2, 0, 3, 1],
       [1, 0, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

## Troviamo elementi duplicati all-interno di un array
Trovare gli elemenri presenti almento 2 volte in un array:

In [2]:
np.random.seed(42)
a = np.random.randint(5,size = 10)
a

array([3, 4, 2, 4, 4, 1, 2, 2, 2, 4])

In [4]:
unique_el, counts = np.unique(a, return_counts=True)

In [5]:
unique_el

array([1, 2, 3, 4])

In [6]:
counts

array([1, 4, 1, 4], dtype=int64)

In [7]:
multiple_el = unique_el[counts>1]
multiple_el

array([2, 4])

In [8]:
np.isin(a, multiple_el)

array([False,  True,  True,  True,  True, False,  True,  True,  True,
        True])

## Eseguire il `drop` dei valori non disponibili (drop na values): 

In [60]:
np.random.seed(42)
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

In [61]:
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])